"""empty message

Revision ID: 03de945e8fe1
Revises: 68a4c0e5de97
Create Date: 2018-02-21 11:26:02.730066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03de945e8fe1'
down_revision = '68a4c0e5de97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
